#---------------------------------------------------------------------------------------#
#I confirm that the attached is my own work, except where clearly indicated in the text.#
#---------------------------------------------------------------------------------------#


#my.rnorm :    generator of normal distribution numbers
#my.rchisq:    generator of chi-square distributed numbers
#my.rt:        generator of T distribution numbers
#
#test.rnorm:   test R function rnorm
#test.rchisq:  test R function rchisq
#test.rf:      test R function rf
#
#mytest.rnorm: test user-created function my.rnorm
#mytest.rchisq:test user-created function my.rchisq
#mytest.rt:    test user-created function my.rt

#----------------------------------------Function my.rnorm-----------------------------------------------#
# Function my.rnorm is used to generate n normally distributed random numbers
#
# Args:
#    n: Numbers needed to be generated
#    mean: Central tendency of distribution,default=0
#    sd: Standrard Deviation,default=1
#
# Returns: numbers are generated according to inputs of arguments

my.rnorm<-function(n,mean=0,sd=1){
  if(!is.numeric(n)||n<0||sd<0||!round(n)==n)
    stop ("invalid arguments.")               #Error handling
  
  i<-1
  outcome<-numeric(i)                         #Create blank vector to store the generated numbers
  for (i in 1:n){
    repeat{                                   #Create two valid uniform numbers 
      u1<-2*runif(1,0,1)-1
      u2<-2*runif(1,0,1)-1                    #'runif' generates uniformly distributed value
      if (u1*u1+u2*u2<1)
        break
    }
    w<-u1*u1+u2*u2                            #Produce two normally distributed numbers
    v=sqrt(-2*log(w)/w)
    X1=(u1*v)*sd+mean
    X2=(u2*v)*sd+mean
    
    #The Algorithm will generate A PAIR numbers, both are normally distributed
    #Randomly choose one number with function "Sample" and add it to output results 
    
    outcome[i]<-sample(c(X1,X2),1)
  }
  return(outcome)
}
#------------------------------------End of my.rnorm Function-------------------------------------------#


#-------------------------------------Function myrchisq.rnorm-------------------------------------------#
# Function my.rchisq is used to generate n numbers which are sum of the squared standrad normal variables. 
#
# Args:
#    n: Numbers needed to be generated
#    df: Degree of Freedom,default=1
#
# Returns: numbers are subject to chi-square distributed according to inputs of arguments

my.rchisq<-function(n,df=1){
  
  
  if(!is.numeric(n)||n<0||df<1||!round(n)==n)   #Error handling
    stop ("invalid arguments.")
  i<-1
  outcomechi<-numeric(i)                        #Create blank vector to store the results
  for (i in 1:n){                               #Generate chi-square distribution numbers
    X<-sum((my.rnorm(df))^2)
    outcomechi[i]<-X                            #Add numbers to output vectors
  }
  return(outcomechi)
}
#------------------------------------End of my.rchisq Function-------------------------------------------#


#----------------------------------------Function my.rt--------------------------------------------------#
#Function my.rnorm is used to generate t-distribution numbers
#
# Args:
#    n: Numbers needed to be generated
#    df: Degree of Freedom,default=1
#
# Returns: numbers are generated according to inputs of arguments


my.rt<-function(n,df=1){
  if(!is.numeric(n)||n<0||!round(n)==n||df<0)     #Error handling
    stop ("invalid arguments.")
  
  i<-1
  outcomet<-numeric(i)                            #Create blank vector to store the results
  
  for (i in 1:n){                                 #Generate T-distribution numbers
    X<-my.rnorm(1,0,1)/sqrt((my.rchisq(1,df))/df)
    outcomet[i]<-X                                #Add numbers to output vectors
  }
  return(outcomet)
}
#--------------------------------------End of my.rt Function---------------------------------------------#


#--------------------------------------Function test.rnorm---------------------------------------------#
#Function test.rnorm is used to test rnorm
#Variables: 
#           ncount,ncount2--Deliver count of numbers to argument n in rnorm
#           nsd,nsd2--Deliver a standard deviation to arguments sd in rnorm           
#           nmean,nmean2--Deliver a mean value to arguments mean in rnorm
#
# Step One: Data validation.
#        A: Test if the input is valid argument for rnorm, if not, test function
#           will require to input again.
#        B: Test if the count of generated numbers is consistent with request of users
#
# Step Two: Test of Normality
#           test.rnorm function requests to assign arguments to rnorm
#           By testing with function shapiro.test and graphically method, judge whether
#           those numbers generated by rnorm are normally distributed.



test.rnorm<-function(){
  
  #Beginning of Step One
  cat("Step One: \n","Validation of Results.")
  
  #Assign numbers to varaibles
  #Error Handling, also testing whether input is invalid
  #If intentionally input valid number for rnorm, test will figure out and require to input again.
  
  repeat{
    ncount<-as.numeric(readline(prompt="How many numbers do you want to generate by rnorm: "))
    
    nmean<-as.numeric(readline(prompt="Assign a mean to rnorm:  "))
    
    nsd<-as.numeric(readline(prompt="Assign standard deviation to rnorm:  "))
    
    testvalid<-try(rnorm(ncount,nmean,nsd))
    
    if (inherits(testvalid,"try-error")==TRUE){
      cat("This test have recognised you have input invalid numbers at rnorm\nTest PASSED!\n")
      cat("Invalid Arguments in rnorm, Please Input Valid Arguments\n")
    }
    
    if (inherits(testvalid,"try-error")==FALSE)
      break
    
  }
  
  #Test of whether my.rnorm create required counts of numbers
  
  y<-rnorm(ncount,mean=nmean,sd=nsd)
  
  z<-length(y)==as.numeric(ncount)&is.numeric(y)
  
  if(z=='TRUE'){
    cat("The length of results is:",length(y), "equals to count of numbers:",ncount,"\n",
        "Results are numeric.\n",
        "TEST PASSED.\n","\n")
  }
  
  
  #Begin of Step Two
  #Error handling and assign numbers to variables
  
  cat("Step Two: \n","Test of Normality for rnorm.")
  
  ncount2<-as.numeric(readline(prompt="What is your sample size: "))
  
  while(ncount2<3||ncount>5000){
    cat("Input a number between 3 and 5000 to create a proper sample.")
    ncount2<-as.numeric(readline(prompt="What is your sample size: "))
  }
  
  nmean2<-as.numeric(readline(prompt="Assign a mean to rnorm:  "))
  
  nsd2<-as.numeric(readline(prompt="Assign standard deviation to rnorm:  "))
  
  while(nsd2<0||!is.numeric(nsd)){
    cat("Invalid Arguments in my.rnorm, Please Input a number >= 0")
    nsd<2-as.numeric(readline(prompt="Assign standard deviation to rnorm:  "))
  }
  
  #Test of Normality by using internal function shapiro.test
  
  testresult<-shapiro.test(rnorm(ncount2,nmean2,nsd2))
  
  #testresult[2] is p-value
  mypvalue<-testresult[2]
  
  if (mypvalue>0.05){
    print(testresult)
    cat("Test of normality indicated numbers created by rnorm are subject to normal distribution at 95% confidence level. 
        \nThe graphical comparison between rnorm are displayed at plot area. ")
  }else{
    cat("Please revise sample size.")  
  }
  
  #Graphically present
  windows(title = "Test of Normality",width = 8,height=4)
  par(mfrow=c(1,2))
  
  resultforchart<-rnorm(ncount2,nmean2,nsd2)
  
  #create QQ plot
  
  qqnorm(resultforchart,main="Normal Q-Q Plot",xlab="",col="lightgreen")
  qqline(resultforchart,col="blue",qtype=4)
  
  #Create Histogram
  
  hist(resultforchart,freq=FALSE,col="lightgreen",main = "Histogram",xlab="")
  curve(dnorm(x,mean=mean(resultforchart),sd=sd(resultforchart)),add=TRUE,col="darkblue")
}
#--------------------------------------End of test.rnorm-----------------------------------------------#



#--------------------------------------Function test.rchisq--------------------------------------------#
#Function test.rchisq is used to test rchisq
#Variables: 
#           ncount--Deliver count of numbers to argument n in rchisq
#           ndf--Deliver a degree of freedom to arguments df in rchisq           
#
#Step:
#           Minds are similar to test.rnorm, test will be perform statistically and graphically
#           Here we use K-S test to conclude whether result is statistical significant and
#           subject to Chi-square distribution.
#
test.rchisq<-function(){
  
  #Beginning
  
  cat("Validation of Results.")
  
  #Assign numbers to variables
  #Error Handling, also testing whether input in rchisq is invalid
  #If invalid, input again
  
  repeat{
    ncount<-as.numeric(readline(prompt="How many numbers do you want to generate by rchisq: "))
    
    ndf<-as.numeric(readline(prompt="Assign degree of freedom to rchisq:  "))
    
    testvalid<-try(rchisq(ncount,ndf))
    
    if (inherits(testvalid,"try-error")==TRUE){
      cat("This test have recognised you have input invalid numbers at rchisq\nTest PASSED!\n")
      cat("Invalid Arguments in rchisq, Please Input Valid Arguments\n")
    }
    
    if (inherits(testvalid,"try-error")==FALSE)
      break
    
  }
  
  y<-rchisq(ncount,df=ndf)
  
  z<-length(y)==as.numeric(ncount)&is.numeric(y)
  
  if(z=='TRUE'){
    cat("The length of results is:",length(y), "equals to count of numbers:",ncount,"\n",
        "Results are numeric.\n",
        "TEST PASSED.\n","\n")
  }
  
  #K-S test: verify if rchisq generates chi-square distributed numbers
  
  cat("Function will use K-S test to see if rchisq is subject to chi-squared distribution.\n")
  
  resultrchi<-rchisq(ncount,ndf)
  
  testresult<-ks.test(resultrchi,"pchisq",ndf)
  
  pvalue<-testresult[2]
  
  cat("P-value is:",as.numeric(pvalue),"\n")
  
  #Judge p-value  
  
  if (pvalue>0.01){
    print(testresult)
    cat("Result is not statistically significant at 99% confidence level.
        \nrchisq has created chi-square distributed numbers
        \nThe standard chi-square density distribution are opened in new windows, Please take as reference. ")
  }else{
    cat("Please revise sample size.")  
  }    
  
  #Graphically present
  #Create standard chi-square density distribution
  
  windows(title = "Reference chi-square distribution",width = 6,height = 6)
  x<-seq(0,10,length.out=1000)
  y<-dchisq(x,1)
  
  plot(x,y,col="red",xlim=c(0,5),ylim=c(0,2),type='l',
       xaxs="i", yaxs="i",ylab='density',xlab='',
       main="Reference: Density of chi-square distribution")
  lines(x,dchisq(x,2),col="lightgreen")
  lines(x,dchisq(x,3),col="darkblue")
  lines(x,dchisq(x,8),col="yellow")
  lines(x,dchisq(x,20),col="pink")
  legend("topleft",legend=paste("df",c(1,2,3,8,20)), lwd=1, col=c("red", "lightgreen","darkblue","yellow","pink"))
}
#--------------------------------------End of test.rchisq-----------------------------------------------#




#-----------------------------------------Function test.rf-----------------------------------------------#
#Function test.rf is used to test rf
#Variables: 
#           ncount--Deliver count of numbers to argument n in rf
#           ndf1--Deliver a degree of freedom 1 to arguments df1 in rf           
#           ndf2--Deliver a degree of freedom 2 to arguments df2 in rf 
#Step:
#           Minds are similar to test.rnorm, test will be perform statistically and graphically
#           Since samples created by rf are F distributed, here we use K-S test to 
#           conclude whether result is statistical significant.          
#
test.rf<-function(){
  
  #Beginning
  
  cat("Validation of Results.")
  
  #Assign numbers to variables
  #Error Handling, also testing whether input is invalid
  #If invalid, input again
  
  repeat{
    ncount<-as.numeric(readline(prompt="How many numbers do you want to generate rf: "))
    
    ndf1<-as.numeric(readline(prompt="Assign degree of freedom 1 to rf:  "))
    
    ndf2<-as.numeric(readline(prompt="Assign degree of freedom 2 to rf:  "))
    
    testvalid<-try(rf(ncount,ndf1,ndf2))
    
    if (inherits(testvalid,"try-error")==TRUE){
      cat("This test have recognised you have input invalid numbers at rf\nTest PASSED!\n")
      cat("Invalid Arguments in rf, Please Input Valid Arguments\n")
    }
    
    if (inherits(testvalid,"try-error")==FALSE)
      break
    
  }
  
  y<-rf(ncount,df1=ndf1,df2=ndf2)
  
  z<-length(y)==as.numeric(ncount)&is.numeric(y)
  
  if(z=='TRUE'){
    cat("The length of results is:",length(y), "equals to count of numbers:",ncount,"\n",
        "Results are numeric.\n",
        "TEST PASSED.\n","\n")
    
    #K-S test: verify if rchisq generates chi-square distributed numbers
    
    cat("Function will use K-S test to see if rf is subject F distribution. \n")
    
    resultrf<-rf(ncount,ndf1,ndf2)
    
    testresult<-ks.test(resultrf,"pf",ndf1,ndf2)
    
    pvalue<-testresult[2]
    
    cat("P-value is:",as.numeric(pvalue),"\n")
    
    #Judge p-value  
    
    if (pvalue>0.05){
      print(testresult)
      cat("Result is not statistically significant at 95% confidence level.
          \nrf has created F distributed numbers.\n")
      
    }else{
      cat("Please revise sample size.")  
    }    
  }
}
#-----------------------------------------End of test.rf-------------------------------------------------#



#--------------------------------------Function mytest.rnorm---------------------------------------------#
#Function mytest.rnorm is used to test my.rnorm
#Variables: 
#           ncount,ncount2--Deliver count of numbers to argument n in my.rnorm
#           nsd,nsd2--Deliver a standard deviation to arguments sd in my.rnorm           
#           nmean,nmean2--Deliver a mean value to arguments mean in my.rnorm
#
# Step One: Data validation.
#        A: Test if the input is valid argument for my.rnorm, if not, test function
#           will require to input again.
#        B: Test if the count of generated numbers is consistent with request of users
#
# Step Two: Test of Normality
#           mytest.rnorm function requests to assign arguments to rnorm and my.rnorm
#           By testing with function shapiro.test and graphically method, judge whether
#           those numbers generated by my.rnorm are normally distributed.
#        


mytest.rnorm<-function(){
  
  #Beginning of Step One
  cat("Step One: \n","Validation of Results.")
  
  #Assign numbers to varaibles
  #Error Handling, also testing whether input in my.rnorm is invalid
  #If intentionally input valid number for my.rnorm, test will figure out and require to input again.
  
  repeat{
    ncount<-as.numeric(readline(prompt="How many numbers do you want to generate by my.rnorm: "))
    
    nmean<-as.numeric(readline(prompt="Assign a mean to my.rnorm:  "))
    
    nsd<-as.numeric(readline(prompt="Assign standard deviation to my.rnorm:  "))
    
    testvalid<-try(my.rnorm(ncount,nmean,nsd))
    
    if (inherits(testvalid,"try-error")==TRUE){
      cat("This test have recognised you have input invalid numbers at my.rnorm\nTest PASSED!\n")
      cat("Invalid Arguments in my.rnorm, Please Input Valid Arguments\n")
    }
    
    if (inherits(testvalid,"try-error")==FALSE)
      break
    
  }
  
  #Test of whether my.rnorm create required counts of numbers
  
  y<-my.rnorm(ncount,mean=nmean,sd=nsd)
  
  z<-length(y)==as.numeric(ncount)&is.numeric(y)
  
  if(z=='TRUE'){
    cat("The length of results is:",length(y), "equals to count of numbers:",ncount,"\n",
        "Results are numeric.\n",
        "TEST PASSED.\n","\n")
  }
  
  
  #Begin of Step Two
  #Error handling and assign numbers to variables
  
  cat("Step Two: \n","Test of Normality for my.rnorm.")
  
  ncount2<-as.numeric(readline(prompt="What is your sample size: "))
  
  while(ncount2<3||ncount>5000){
    cat("Input a number between 3 and 5000 to create a proper sample.")
    ncount2<-as.numeric(readline(prompt="What is your sample size: "))
  }
  
  nmean2<-as.numeric(readline(prompt="Assign a mean to my.rnorm:  "))
  
  nsd2<-as.numeric(readline(prompt="Assign standard deviation to my.rnorm:  "))
  
  while(nsd2<0||!is.numeric(nsd)){
    cat("Invalid Arguments in my.rnorm, Please Input a number >= 0")
    nsd<2-as.numeric(readline(prompt="Assign standard deviation to my.rnorm:  "))
  }
  
  #Test of Normality by using internal function shapiro.test
  
  testresult<-shapiro.test(my.rnorm(ncount2,nmean2,nsd2))
  
  #testresult[2] is p-value
  mypvalue<-testresult[2]
  
  if (mypvalue>0.05){
    print(testresult)
    cat("Test of normality indicated numbers created by my.rnorm are subject to normal distribution at 95% confidence level. 
        \nThe graphical comparison between rnorm and my.rnorm are displayed at plot area. ")
  }else{
    cat("Please revise sample size.")  
  }
  
  #Graphical Comparison between rnorm and my.rnorm
  windows(title = "Comparison between rnorm and my.rnorm",width = 8,height=4)
  par(mfrow=c(1,2))
  resultforchartA<-my.rnorm(ncount2,nmean2,nsd2)
  resultforchartB<-rnorm(ncount2,nmean2,nsd2)
  hist(resultforchartA,freq=FALSE,col="lightgreen",main = "Hist from my.rnorm",xlab="")
  curve(dnorm(x,mean=mean(resultforchartA),sd=sd(resultforchartA)),add=TRUE,col="darkblue")
  hist(resultforchartB,freq=FALSE,col="lightgreen",main = "Hist from rnorm",xlab="")
  curve(dnorm(x,mean=mean(resultforchartB),sd=sd(resultforchartB)),add=TRUE,col="darkblue")
}
#--------------------------------------End of mytest.rnorm-----------------------------------------------#


#--------------------------------------Function mytest.rchisq--------------------------------------------#
#Function mytest.rchisq is used to test my.rnorm
#Variables: 
#           ncount--Deliver count of numbers to argument n in my.rchisq
#           ndf--Deliver a standard deviation to arguments df in my.rchisq           
#
#Step:
#           Minds are similar to mytest.rnorm, test will be perform statistically and graphically
#           Since samples created by rchisq are chi-square distributed, here we use KS test to compare
#           if result is statistical significant between the sample created by my.rchisq and rchisq
#
mytest.rchisq<-function(){
  
  #Beginning
  
  cat("Validation of Results.")
  
  #Assign numbers to variables
  #Error Handling, also testing whether input in my.rchisq is invalid
  #If invalid, input again
  
  repeat{
    ncount<-as.numeric(readline(prompt="How many numbers do you want to generate by my.rchisq: "))
    
    ndf<-as.numeric(readline(prompt="Assign degree of freedom to my.rchisq:  "))
    
    testvalid<-try(my.rchisq(ncount,ndf))
    
    if (inherits(testvalid,"try-error")==TRUE){
      cat("This test have recognised you have input invalid numbers at my.rchisq\nTest PASSED!\n")
      cat("Invalid Arguments in my.rchisq, Please Input Valid Arguments\n")
    }
    
    if (inherits(testvalid,"try-error")==FALSE)
      break
    
  }
  
  y<-my.rchisq(ncount,df=ndf)
  
  z<-length(y)==as.numeric(ncount)&is.numeric(y)
  
  if(z=='TRUE'){
    cat("The length of results is:",length(y), "equals to count of numbers:",ncount,"\n",
        "Results are numeric.\n",
        "TEST PASSED.\n","\n")
    
    #K-S test: verify if my.rchisq generates chi-square distributed numbers
    #Create two vectors by rchisq and my.rchisq respectively  
    
    cat("Function will create two samples, one from rchisq where numbers subject to chi-square distribution,
        the other from my.rchisq \n")
    
    resultrchi<-rchisq(ncount,ndf)
    
    resultmyrchi<-my.rchisq(ncount,ndf)
    
    testresult<-ks.test(resultrchi,resultmyrchi)
    
    pvalue<-testresult[2]
    
    #Judge p-value  
    
    if (pvalue>0.05){
      print(testresult)
      cat("Result is not statistically significant at 95% confidence level.
          \nmy.rchisq has created chi-square distributed numbers
          \nThe graphical comparison between rchisq and my.rchisq are displayed at plot area. ")
    }else{
      cat("Please revise sample size.")  
    }    
    
    #Graphical Comparison between rnorm and my.rnorm
    
    windows(title = "Comparison between rchisq and my.rchisq",width = 6,height=3)
    
    par(mfrow=c(1,2))
    
    plot(density(rchisq(ncount,ndf)),main = "rchisq")
    
    plot(density(my.rchisq(ncount,ndf)),main="my.rchisq")
  }
  }
#--------------------------------------End of mytest.rchisq-----------------------------------------------#


#-----------------------------------------Function mytest.rt----------------------------------------------#
#Function mytest.rchisq is used to test my.rnorm
#Variables: 
#           ncount--Deliver count of numbers to argument n in my.rt
#           ndf--Deliver a standard deviation to arguments df in my.rt           
#
#Step:
#           Minds are similar to mytest.rchisq, test will be perform statistically and graphically
#           Since samples created by rt are t distributed, here we use KS test to compare my.rt and rt
#           if result is statistical significant between the sample created by my.rt and rt
#

mytest.rt<-function(){
  
  #Beginning
  cat("Validation of Results.")
  
  #Assign numbers to variables
  #Error Handling, also testing whether input in my.rt is invalid
  #If invalid, input again
  
  repeat{
    ncount<-as.numeric(readline(prompt="How many numbers do you want to generate by my.rt: "))
    
    ndf<-as.numeric(readline(prompt="Assign degree of freedom to my.rt:  "))
    
    testvalid<-try(my.rt(ncount,ndf))
    if (inherits(testvalid,"try-error")==TRUE){
      cat("This test have recognised you have input invalid numbers at my.rt\nTest PASSED!\n")
      cat("Invalid Arguments in my.rt, Please Input Valid Arguments\n")
    }
    
    if (inherits(testvalid,"try-error")==FALSE)
      break
    
  }
  
  y<-my.rt(ncount,df=ndf)
  
  z<-length(y)==as.numeric(ncount)&is.numeric(y)
  
  if(z=='TRUE'){
    cat("The length of results is:",length(y), "equals to count of numbers:",ncount,"\n",
        "Results are numeric.\n",
        "TEST PASSED.\n","\n")
    
    #K-S test: verify if my.rt generates t distributed numbers
    #Create two vectors by rt and my.rt respectively  
    
    cat("Function will create two samples, one from rt where numbers subject to t distribution,
        the other from my.rt \n")
    
    resultrt<-rt(ncount,ndf)
    
    resultmyrt<-my.rt(ncount,ndf)
    
    testresult<-ks.test(resultrt,resultmyrt)
    
    pvalue<-testresult[2]
    
    #Judge p-value  
    
    if (pvalue>0.05){
      print(testresult)
      cat("Result is not statistically significant at 95% confidence level.
          \nmy.rt has created t distributed numbers
          \nThe graphical comparison between rt and my.rt are displayed at plot area. ")
    }else{
      cat("Please revise sample size.")  
    }    
    
    #Graphical Comparison between rt and my.rt
    
    windows(title = "Comparison between rt and my.rt",width = 6,height=3)
    
    par(mfrow=c(1,2))
    
    plot(density(rt(ncount,ndf)),main = "rt")
    
    plot(density(my.rt(ncount,ndf)),main="my.rt")
  }
  }
#----------------------------------------End of mytest.rt-------------------------------------------------#